site_name: Theme.Park Docs
site_description: Here you can find installation and setup details for all the themes in the GilbN/theme.park repo
site_author: GilbN
site_url: https://docs.theme-park.dev

repo_url: https://github.com/GilbN/theme.park/
repo_name: GilbN/theme.park

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - lightgallery
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup: setup.md
  - Themes:
      Apps that support custom css âš™ï¸: themes/sonarr.md
      Apps that require special setup âš ï¸: themes/sonarr.md
      Apps that support Docker Mods ğŸ³: themes/sonarr.md
      Apps that support Custom scripts ğŸ”¥: themes/sonarr.md
      Sonarr ğŸ³ğŸ”¥: themes/sonarr.md
      Radarr ğŸ³ğŸ”¥: themes/radarr.md
      Lidarr ğŸ³ğŸ”¥: themes/lidarr.md
      Readarr ğŸ³ğŸ”¥: themes/readarr.md
      Bazarr ğŸ³ğŸ”¥: themes/bazarr.md
      Plex ğŸ³ğŸ”¥: themes/plex.md
      Jellyfin ğŸ³ğŸ”¥: themes/jellyfin.md
      Tautulli ğŸ³ğŸ”¥: themes/tautulli.md
      Nzbget ğŸ³ğŸ”¥: themes/nzbget.md
      Deluge ğŸ³ğŸ”¥: themes/deluge.md
      ruTorrent ğŸ³ğŸ”¥: themes/rutorrent.md
      Jackett ğŸ³ğŸ”¥: themes/jackett.md
      Librespeed ğŸ³ğŸ”¥: themes/librespeed.md
      Synclounge ğŸ³ğŸ”¥: themes/synclounge.md
      TheLounge ğŸ³ğŸ”¥: themes/thelounge.md
      Lazylibrarian ğŸ³ğŸ”¥: themes/lazylibrarian.md
      CalibreWeb ğŸ³ğŸ”¥: themes/calibreweb.md
      Transmission ğŸ³ğŸ”¥: themes/transmission.md
      Sabnzbd ğŸ³ğŸ”¥âš ï¸: themes/sabnzbd.md
      qBittorrent ğŸ³ğŸ”¥âš ï¸: themes/qbittorrent.md
      Pihole âš ï¸: themes/pihole.md
      Dozzle âš ï¸: themes/dozzle.md
      Organizr âš™ï¸: themes/organizr.md
      Unraid âš™ï¸: themes/unraid.md
      Ombi âš™ï¸: themes/ombi.md
      Grafana âš™ï¸: themes/grafana.md
      Filebrowser âš™ï¸: themes/filebrowser.md
      Monitorr âš™ï¸: themes/monitorr.md
      Logarr âš™ï¸: themes/logarr.md
      Gitea âš™ï¸: themes/gitea.md
      Nzbhydra2: themes/nzbhydra2.md
      Portainer: themes/portainer.md
      Guacamole: themes/guacamole.md
      Netdata: themes/netdata.md
      PLPP: themes/plpp.md
      Requestrr: themes/requestrr.md
      Adguard: themes/adguard.md
      Gaps: themes/gaps.md
      Bitwarden: themes/bitwarden.md
      Duplicacy: themes/duplicacy.md
      Kitana: themes/kitana.md
      Webtools: themes/webtools.md
      Resilio-Sync: themes/resilio-sync.md
      Moviematch: themes/moviematch.md
      Petio: themes/petio.md
      Flood: themes/flood.md
  - Addons:
      Sonarr: themes/addons/sonarr/index.md
      Radarr: themes/addons/radarr/index.md
      Bazarr: themes/addons/bazarr/index.md
      Organizr: themes/addons/organizr/index.md
      Unraid:
        Retro Terminal: themes/addons/unraid/login-page/retro-terminal/index.md
        Alien: themes/addons/unraid/login-page/alien/index.md
        Fallout: themes/addons/unraid/login-page/fallout/index.md
  - Colors:
      Organizr Dark: colors/organizr-dark.md
      Dark: colors/dark.md
      Aquamarine: colors/aquamarine.md
      Space Gray: colors/space-gray.md
      Plex: colors/plex.md
      Hotline: colors/hotline.md

  - Custom Themes: /themes/custom

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: site_assets/favicon.ico
  logo: site_assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: red
      accent: light green

extra:
  homepage: https://github.com/GilbN/theme.park
  addons:
    sonarr:
      4K Logo:
        path: themes/addons/sonarr
    radarr:
      4K Logo:
        path: themes/addons/radarr
    bazarr:
      4K Logo:
        path: themes/addons/bazarr
    organizr:
      Organizr Glass:
        path: themes/addons/organizr
    unraid:
      Alien:
        path: themes/addons/unraid/login-page/alien
      Fallout:
        path: themes/addons/unraid/login-page/fallout
      Retro Terminal:
        path: themes/addons/unraid/login-page/retro-terminal
