site_name: theme.park Docs
site_description: Here you can find installation and setup details for all the themes in the themepark-dev/theme.park repo
site_author: GilbN
site_url: https://docs.theme-park.dev

repo_url: https://github.com/themepark-dev/theme.park/
repo_name: themepark-dev/theme.park
edit_uri: https://github.com/GilbN/tp-docs/edit/main/docs/

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros
  - include-markdown
  - redirects:
      redirect_maps:
        discord.md: "https://discord.gg/HM5uUKU"
        dockerhub.md: "https://hub.docker.com/u/gilbn"
        github.md: "https://github.com/gilbn"
        ghcr.md: "https://github.com/users/GilbN/packages/container/package/theme.park"
        donate.md: "index.md#donation"
        themes.md: "themes/sonarr.md"
        docker-mods.md: "setup/index.md#docker-mods"
        hotio.md: "setup/index.md#hotio-containers-s6-overlay-images"

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup: setup/index.md
  - Themes:
      âš™ï¸ App supports custom CSS: /themes/
      ğŸ³ Supports Docker Mods: /docker-mods/
      ğŸ”¥ Supports Hotio / S6-Overlay images: /hotio/
      âš ï¸ Require Special Setup: /themes/
      âŒ Deprecated: /themes/
      Sonarr ğŸ³ğŸ”¥âš ï¸: themes/sonarr.md
      Radarr ğŸ³ğŸ”¥âš ï¸: themes/radarr.md
      Lidarr ğŸ³ğŸ”¥âš ï¸: themes/lidarr.md
      Readarr ğŸ³ğŸ”¥âš ï¸: themes/readarr.md
      Prowlarr ğŸ³ğŸ”¥âš ï¸: themes/prowlarr.md
      Whisparr ğŸ³ğŸ”¥âš ï¸: themes/whisparr.md
      Bazarr ğŸ³ğŸ”¥: themes/bazarr.md
      Plex ğŸ³ğŸ”¥: themes/plex.md
      Jellyfin âš™ï¸: themes/jellyfin.md
      Emby ğŸ³âš ï¸: themes/emby.md
      Overseerr: themes/overseerr.md
      Tautulli ğŸ³ğŸ”¥: themes/tautulli.md
      Nzbget ğŸ³ğŸ”¥: themes/nzbget.md
      ruTorrent ğŸ³ğŸ”¥: themes/rutorrent.md
      Sabnzbd ğŸ³ğŸ”¥âš ï¸: themes/sabnzbd.md
      VueTorrent ğŸ³ğŸ”¥âš ï¸: themes/vuetorrent.md
      qBittorrent ğŸ³ğŸ”¥âš ï¸: themes/qbittorrent.md
      Deluge ğŸ³: themes/deluge.md
      Jackett ğŸ³ğŸ”¥: themes/jackett.md
      Librespeed ğŸ³: themes/librespeed.md
      Synclounge ğŸ³: themes/synclounge.md
      Lazylibrarian ğŸ³: themes/lazylibrarian.md
      CalibreWeb ğŸ³âš ï¸: themes/calibreweb.md
      Transmission ğŸ³: themes/transmission.md
      Mylar 3 ğŸ³âš ï¸: themes/mylar3.md
      Duplicati ğŸ³: themes/duplicati.md
      Nginx-Proxy-Manager ğŸ”¥: themes/nginx-proxy-manager.md
      Xbackbone âš™ï¸: themes/xbackbone.md
      Filebrowser âš™ï¸: themes/filebrowser.md
      Organizr âš™ï¸: themes/organizr.md
      Unraid âš™ï¸: themes/unraid.md
      Ombi âš™ï¸: themes/ombi.md
      Gitea âš™ï¸: themes/gitea.md
      Pihole âš ï¸: themes/pihole.md
      Dozzle âš ï¸: themes/dozzle.md
      Bitwarden âš ï¸: themes/bitwarden.md
      Vaultwarden âš ï¸: themes/bitwarden/#vaultwarden
      Authelia âš ï¸: themes/authelia.md
      Nzbhydra2: themes/nzbhydra2.md
      Portainer: themes/portainer.md
      Guacamole: themes/guacamole.md
      Netdata: themes/netdata.md
      Requestrr: themes/requestrr.md
      Adguard: themes/adguard.md
      Gaps: themes/gaps.md
      Duplicacy: themes/duplicacy.md
      Kitana: themes/kitana.md
      Resilio-Sync: themes/resilio-sync.md
      Moviematch: themes/moviematch.md
      Petio: themes/petio.md
      Flood: themes/flood.md
      Audiobookshelf: themes/audiobookshelf.md
      Uptime-Kuma: themes/uptime-kuma.md
      Docmost: themes/docmost.md
      TheLounge âŒğŸ³: themes/thelounge.md
      Grafana âŒâš™ï¸: themes/grafana.md
      Monitorr âŒâš™ï¸: themes/monitorr.md
      Logarr âŒâš™ï¸: themes/logarr.md
      PLPP âŒ: themes/plpp.md
      Webtools âŒ: themes/webtools.md
  - Addons:
      Addons: themes/addons/index.md
      Sonarr:
        Sonarr 4K Logo: themes/addons/sonarr/sonarr-4k-logo
        Sonarr 4K Text Logo: themes/addons/sonarr/sonarr-4k-text-logo
        Sonarr Darker: themes/addons/sonarr/sonarr-darker
        Sonarr Text Logo: themes/addons/sonarr/sonarr-text-logo
        Sonarr 4K Favicon: themes/addons/sonarr/sonarr-4k-favicon
        Sonarr Anime Favicon: themes/addons/sonarr/sonarr-anime-favicon
        Sonarr Anime Blue Favicon: themes/addons/sonarr/sonarr-anime-blue-favicon
      Radarr:
        Radarr 4K Logo: themes/addons/radarr/radarr-4k-logo
        Radarr Darker: themes/addons/radarr/radarr-darker
        Alternative Calendar: themes/addons/radarr/radarr-alt-calendar
        Radarr Anime Logo: themes/addons/radarr/radarr-anime-logo
        Radarr 4K Favicon: themes/addons/radarr/radarr-4k-favicon
        Radarr Anime Favicon: themes/addons/radarr/radarr-anime-favicon
      Readarr:
        Readarr Alternative Logo: themes/addons/readarr/readarr-alt-logo
        Readarr Darker: themes/addons/readarr/readarr-darker
        Readarr Alternative Calendar: themes/addons/readarr/readarr-alt-calendar
        Readarr Text Logo: themes/addons/readarr/readarr-text-logo
        Readarr Alt Favicon: themes/addons/readarr/readarr-alt-favicon
      Bazarr:
        Bazarr 4K Logo: themes/addons/bazarr/bazarr-4k-logo
        Bazarr Darker: themes/addons/bazarr/bazarr-darker
      Lidarr:
        Lidarr Darker: themes/addons/lidarr/lidarr-darker
        Lidarr Alternative Calendar: themes/addons/lidarr/lidarr-alt-calendar
      Prowlarr:
        Prowlarr Darker: themes/addons/prowlarr/prowlarr-darker
        Prowlarr Text Logo: themes/addons/prowlarr/prowlarr-text-logo
      Whisparr:
        Whisparr Darker: themes/addons/whisparr/whisparr-darker
        Whisparr Alternative Calendar: themes/addons/whisparr/whisparr-alt-calendar
      Organizr: themes/addons/organizr/index.md
      Unraid:
        Retro Terminal: themes/addons/unraid/login-page/retro-terminal/index.md
        Alien: themes/addons/unraid/login-page/alien/index.md
        Fallout: themes/addons/unraid/login-page/fallout/index.md
      Plex:
        Alternative Logo: themes/addons/plex/plex-alt-logo/index.md
        Overseerr Side Menu: themes/addons/plex/overseerr-side-menu/index.md
      Authelia:
        Login Logo: themes/addons/authelia/authelia-login-logo/index.md
  - Theme Options:
      Theme Options: theme-options/index.md
      Organizr: theme-options/organizr.md
      Dark: theme-options/dark.md
      Dracula: theme-options/dracula.md
      Aquamarine: theme-options/aquamarine.md
      Space Gray: theme-options/space-gray.md
      Plex: theme-options/plex.md
      Hotline: theme-options/hotline.md
      Hotpink: theme-options/hotpink.md
      Overseerr: theme-options/overseerr.md
      Nord: theme-options/nord.md
      Maroon: theme-options/maroon.md
  - Community Themes:
      Community Themes: community-themes/index.md
      Catppuccin: community-themes/catppuccin/index.md
      OneDark: community-themes/onedark/index.md
      Blackberry Themes: community-themes/blackberry-themes/index.md
      Pine Shadow: community-themes/pine-shadow/index.md
      TrueBlack: community-themes/trueblack/index.md
      Ibracorp: community-themes/ibracorp/index.md
      Hotline-Old: community-themes/hotline-old/index.md
      Infinity Stone Themes:
        Mind: community-themes/infinity-stone-themes/mind.md
        Soul: community-themes/infinity-stone-themes/soul.md
        Reality: community-themes/infinity-stone-themes/reality.md
        Power: community-themes/infinity-stone-themes/power.md
        Space: community-themes/infinity-stone-themes/space.md
        Time: community-themes/infinity-stone-themes/time.md
  - Custom Themes: custom/index.md
  - Support: /discord
  - Donate: /donate

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  favicon: site_assets/favicon.ico
  logo: site_assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: red
      accent: light green

extra:
  homepage: https://github.com/themepark-dev/theme.park
  social:
    - icon: fontawesome/solid/heart
      link: "https://docs.theme-park.dev/donate"
      name: Donate
    - icon: fontawesome/brands/discord
      link: "https://docs.theme-park.dev/discord"
      name: Discord
    - icon: fontawesome/brands/docker
      link: "https://github.com/users/GilbN/packages/container/package/theme.park"
      name: Docker
    - icon: fontawesome/brands/github
      link: "https://github.com/gilbn"
      name: GitHub
  addons:
    sonarr:
      Overview:
        path: themes/addons/sonarr
      Sonarr 4K Logo:
        path: themes/addons/sonarr/sonarr-4k-logo
      Sonarr 4K Text Logo:
        path: themes/addons/sonarr/sonarr-4k-text-logo
      Sonarr Anime Logo:
        path: themes/addons/sonarr/sonarr-anime-logo
      Sonarr Anime Text Logo:
        path: themes/addons/sonarr/sonarr-anime-text-logo
      Sonarr Darker:
        path: themes/addons/sonarr/sonarr-darker
      Sonarr Text Logo:
        path: themes/addons/sonarr/sonarr-text-logo
      Sonarr 4K Favicon:
        path: themes/addons/sonarr/sonarr-4k-favicon
      Sonarr Anime Favicon:
        path: themes/addons/sonarr/sonarr-anime-favicon
      Sonarr Anime Blue Favicon:
        path: themes/addons/sonarr/sonarr-anime-blue-favicon
    radarr:
      Radarr 4K Logo:
        path: themes/addons/radarr/radarr-4k-logo
      Radarr Darker:
        path: themes/addons/radarr/radarr-darker
      Alternative Calendar:
        path: themes/addons/radarr/radarr-alt-calendar
      Radarr Anime Logo:
        path: themes/addons/radarr/radarr-anime-logo
      Radarr 4K Favicon:
        path: themes/addons/radarr/radarr-4k-favicon
      Radarr Anime Favicon:
        path: themes/addons/radarr/radarr-anime-favicon
    readarr:
      Alternative Audiobook Logo:
        path: themes/addons/readarr/readarr-alt-logo
      Readarr Darker:
        path: themes/addons/readarr/readarr-darker
      Alternative Calendar:
        path: themes/addons/readarr/readarr-alt-calendar
      Readarr Text Logo:
        path: themes/addons/readarr/readarr-text-logo
      Readarr Alt Favicon:
        path: themes/addons/readarr/readarr-alt-favicon
    bazarr:
      Bazarr 4K Logo:
        path: themes/addons/bazarr/bazarr-4k-logo
      Bazarr Darker:
        path: themes/addons/bazarr/bazarr-darker
    lidarr:
      Lidarr Darker:
        path: themes/addons/lidarr/lidarr-darker
      Alternative Calendar:
        path: themes/addons/lidarr/lidarr-alt-calendar
    prowlarr:
      Prowlarr Darker:
        path: themes/addons/prowlarr/prowlarr-darker
      Prowlarr Text Logo:
        path: themes/addons/prowlarr/prowlarr-text-logo
    whisparr:
      Whisparr Darker:
        path: themes/addons/whisparr/whisparr-darker
      Alternative Calendar:
        path: themes/addons/whisparr/whisparr-alt-calendar
    organizr:
      Organizr Glass:
        path: themes/addons/organizr
    unraid:
      Alien:
        path: themes/addons/unraid/login-page/alien
      Fallout:
        path: themes/addons/unraid/login-page/fallout
      Retro Terminal:
        path: themes/addons/unraid/login-page/retro-terminal
    plex:
      Overseerr Side Menu:
        path: themes/addons/plex/overseerr-side-menu
      Alternative Logo:
        path: themes/addons/plex/plex-alt-logo
  themes:
    - aquamarine
    - hotline
    - hotpink
    - dracula
    - dark
    - organizr
    - space-gray
    - overseerr
    - plex
    - nord
    - maroon

  community_themes:
    - mind
    - power
    - reality
    - soul
    - space
    - time
    - onedark
    - hotline-old
    - blackberry-abyss
    - blackberry-amethyst
    - blackberry-carol
    - blackberry-dreamscape
    - blackberry-flamingo
    - blackberry-hearth
    - blackberry-martini
    - blackberry-pumpkin
    - blackberry-royal
    - blackberry-shadow
    - blackberry-solar
    - blackberry-vanta
    - trueblack
