site_name: theme.park Docs
site_description: Here you can find installation and setup details for all the themes in the GilbN/theme.park repo
site_author: GilbN
site_url: https://docs.theme-park.dev

repo_url: https://github.com/GilbN/theme.park/
repo_name: GilbN/theme.park

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros
  - redirects:
      redirect_maps:
        discord.md: 'https://discord.gg/HM5uUKU'
        dockerhub.md: 'https://hub.docker.com/u/gilbn'
        github.md: 'https://github.com/gilbn'
        ghcr.md: 'https://github.com/users/GilbN/packages/container/package/theme.park'
        donate.md: 'https://docs.theme-park.dev/#donation'
        themes.md: 'https://docs.theme-park.dev/themes/sonarr/'
        addons.md: 'https://docs.theme-park.dev/themes/addons/sonarr'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - lightgallery
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup: setup.md
  - Themes:
      âš™ï¸ Supports custom CSS: /themes/
      âš ï¸ Require Special Setup: /themes/
      ğŸ³ Supports Docker Mods: /themes/
      ğŸ”¥ Supports Hotio Scripts: /themes/
      Sonarr ğŸ³ğŸ”¥: themes/sonarr.md
      Radarr ğŸ³ğŸ”¥: themes/radarr.md
      Lidarr ğŸ³ğŸ”¥: themes/lidarr.md
      Readarr ğŸ³ğŸ”¥: themes/readarr.md
      Bazarr ğŸ³ğŸ”¥: themes/bazarr.md
      Plex ğŸ³ğŸ”¥: themes/plex.md
      Jellyfin ğŸ³ğŸ”¥: themes/jellyfin.md
      Emby ğŸ³: themes/emby.md
      Tautulli ğŸ³ğŸ”¥: themes/tautulli.md
      Nzbget ğŸ³ğŸ”¥: themes/nzbget.md
      ruTorrent ğŸ³ğŸ”¥: themes/rutorrent.md
      Sabnzbd ğŸ³ğŸ”¥âš ï¸: themes/sabnzbd.md
      qBittorrent ğŸ³ğŸ”¥âš ï¸: themes/qbittorrent.md
      Deluge ğŸ³: themes/deluge.md
      Jackett ğŸ³ğŸ”¥: themes/jackett.md
      Librespeed ğŸ³: themes/librespeed.md
      Synclounge ğŸ³: themes/synclounge.md
      TheLounge ğŸ³: themes/thelounge.md
      Lazylibrarian ğŸ³: themes/lazylibrarian.md
      CalibreWeb ğŸ³: themes/calibreweb.md
      Transmission ğŸ³: themes/transmission.md
      Pihole âš ï¸: themes/pihole.md
      Dozzle âš ï¸: themes/dozzle.md
      Organizr âš™ï¸: themes/organizr.md
      Unraid âš™ï¸: themes/unraid.md
      Ombi âš™ï¸: themes/ombi.md
      Grafana âš™ï¸: themes/grafana.md
      Filebrowser âš™ï¸: themes/filebrowser.md
      Monitorr âš™ï¸: themes/monitorr.md
      Logarr âš™ï¸: themes/logarr.md
      Gitea âš™ï¸: themes/gitea.md
      Nzbhydra2: themes/nzbhydra2.md
      Portainer: themes/portainer.md
      Guacamole: themes/guacamole.md
      Netdata: themes/netdata.md
      PLPP: themes/plpp.md
      Requestrr: themes/requestrr.md
      Adguard: themes/adguard.md
      Gaps: themes/gaps.md
      Bitwarden: themes/bitwarden.md
      Duplicacy: themes/duplicacy.md
      Kitana: themes/kitana.md
      Webtools: themes/webtools.md
      Resilio-Sync: themes/resilio-sync.md
      Moviematch: themes/moviematch.md
      Petio: themes/petio.md
      Flood: themes/flood.md
      VueTorrent: themes/vuetorrent.md
  - Addons:
      Sonarr: themes/addons/sonarr/index.md
      Radarr: themes/addons/radarr/index.md
      Bazarr: themes/addons/bazarr/index.md
      Organizr: themes/addons/organizr/index.md
      Unraid:
        Retro Terminal: themes/addons/unraid/login-page/retro-terminal/index.md
        Alien: themes/addons/unraid/login-page/alien/index.md
        Fallout: themes/addons/unraid/login-page/fallout/index.md
  - Colors:
      Organizr Dark: colors/organizr-dark.md
      Dark: colors/dark.md
      Aquamarine: colors/aquamarine.md
      Space Gray: colors/space-gray.md
      Plex: colors/plex.md
      Hotline: colors/hotline.md
  - Custom Themes: custom/index.md
  - Support: /discord
  - Donate: /donate

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  favicon: site_assets/favicon.ico
  logo: site_assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: red
      accent: light green

extra:
  homepage: https://github.com/GilbN/theme.park
  social:
    - icon: fontawesome/solid/heart
      link: 'https://docs.theme-park.dev/donate'
      name: Donate
    - icon: fontawesome/brands/discord
      link: 'https://docs.theme-park.dev/discord'
      name: Discord
    - icon: fontawesome/brands/docker
      link: 'https://github.com/users/GilbN/packages/container/package/theme.park'
      name: Docker
    - icon: fontawesome/brands/github
      link: 'https://github.com/gilbn'
      name: GitHub
  addons:
    sonarr:
      4K Logo:
        path: themes/addons/sonarr
    radarr:
      4K Logo:
        path: themes/addons/radarr
    bazarr:
      4K Logo:
        path: themes/addons/bazarr
    organizr:
      Organizr Glass:
        path: themes/addons/organizr
    unraid:
      Alien:
        path: themes/addons/unraid/login-page/alien
      Fallout:
        path: themes/addons/unraid/login-page/fallout
      Retro Terminal:
        path: themes/addons/unraid/login-page/retro-terminal
